export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const NEW_PRODUCT = 'NEW_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';